### ISSUE TITLE
Is there an advantage in using FIX from Bitstamp vs Websocket?

### ISSUE THREAD

**Issue by sharpcall** [mselser95/Bitstamp-FIX-cpp#1]
Hi,

This is not an issue probably. Can you please describe if there is an advantage or pro to using FIX from Bitstamp vs their Websocket API?

Thanks,

**Comment by mselser95** [comment]
Hello,

Websockets are great, and simpler if you only need to listen to updates. FIX allows you to hear the updates and place orders asynchronously, so it depends on the use case.

**Comment by sharpcall** [comment]
Hi Matias,

Thanks for the explanation.

I thought with one connection to websocket both listening and reading can
be done - No?

So you would say there is an HFT advantage to using FIX with bitstamp VS
websocket since it is asynchronous?

Thanks,

**Comment by mselser95** [comment]
Theoretically yes, it can be done. Not with Bitstamp websocket API though. This websocket API only allowes you to listen to market data or order updates.

See ref: https://www.bitstamp.net/websocket/v2/

FIX is a protocol made for trading, it's specifications handle several types of tags that give a lot of information regarding trading, not only marketdata. Distance is usually the key factor in HFT, not necesarilly the communication protocol. Nevertheless the fact that FIX is asyncronous is a very important factor.

**Comment by sharpcall** [comment]
Interesting.

I understood FIX runs over TCP just like websockets do too. Whatever TCP
ACK message bottleneck there is also applies to FIX.

So what is asynchronous with FIX? Can an order be sent at exact time that
update for price is received and same is not possible with websocket?

I wonder if for example 1000 orders can be sent to Bitstamp and 1000 prices
received in say 1 second using FIX while same process will take 3 seconds
using Websocket. Is that the difference in FIX being asynchronous?

Thanks again,

**Comment by mselser95** [comment]
I understand your question. I do not have benchmarking information to share with you. The difference is mainly related to orders. With FIX, you can send orders, and receive execution reports. This is the main difference with the Bitstamp websockets API. With Bitstamp, you can't place orders using websockets, you have to do it using their rest API. If the API supported websockets to trade, I'm not sure which one would be faster.

**Comment by sharpcall** [comment]
Thanks for the response.

Did you have to ask Bitstamp to enable FIX on your account? Their documentation says so and seem they are taking very long now to do this. You may want to put this in Readme. I have reached out to support with a ticket and calls and they are not sure what FIX is all together and tell me that their API team has a backlog and there is no timeframe which is usually not good news.

**Comment by mselser95** [comment]
Yes, I did. I did it twice. The first time, they took about a week. The second time, they were taking longer than a week and when I asked "they forgot", so you should be patient. Their support takes a while to help.
